set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_SYSTEM_VERSION 1)

set (DEVKITPPC $ENV{DEVKITPPC})
set (DEVKITPRO $ENV{DEVKITPRO})

set (CMAKE_CXX_COMPILER ${DEVKITPPC}/bin/powerpc-eabi-g++)
set (CMAKE_C_COMPILER ${DEVKITPPC}/bin/powerpc-eabi-gcc)

# where is the target environment 
set (CMAKE_FIND_ROOT_PATH  ${DEVKITPPC}
    ${DEVKITPRO}/libogc
    ${DEVKITPRO}/portlibs/ppc)

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
